# Generated by Django 2.2.11 on 2021-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discription',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
