# Generated by Django 3.1.5 on 2021-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210128_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_event',
        ),
        migrations.AddField(
            model_name='event',
            name='team_size_mn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='team_size_mx',
            field=models.IntegerField(default=4),
        ),
    ]
