# Generated by Django 2.2.11 on 2021-01-31 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_size', models.IntegerField(default=1)),
                ('team_id', models.CharField(max_length=100, null=True)),
                ('team_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('team_member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
