# Generated by Django 3.1.5 on 2021-01-31 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='team_not_accepted',
            field=models.ManyToManyField(related_name='pending', to=settings.AUTH_USER_MODEL),
        ),
    ]
