# Generated by Django 3.1.5 on 2021-01-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210128_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
