# Generated by Django 3.1.5 on 2021-01-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210128_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamRegistration',
        ),
    ]
